### ISSUE TITLE
Writing to GA failed

### ISSUE THREAD

**Issue by f0086** [ioBroker/ioBroker.knx#188]
I've imported my ETS project with all the GAs, which worked fine. After starting the KNX instance, the following messages are shown in the log:

```
knx.0 | 2021-07-19 23:24:41.862 | silly | (1297) States user redis pmessage knx.0.*/knx.0.Sensoren.EG.Küche_Temperatur:{"val":24.3,"ack":true,"ts":1626729881860,"q":0,"from":"system.adapter.knx.0","user":"system.user.admin","lc":1626728845974
-- | -- | -- | --
knx.0 | 2021-07-19 23:24:41.859 | info | (1297) STATE_TUNNELING_REQUEST: analyse this case. Gateway sends the same package one more time, may be answer???
knx.0 | 2021-07-19 23:24:41.858 | info | (1297) Change state from STATE_TUNNELLING_REQUEST(13) to STATE_TUNNELLING_REQUEST(13)
knx.0 | 2021-07-19 23:24:41.857 | info | (1297) WRITE : mappedName : Küche Temperatur dest : 5/1/3 val: 24.3 (DPT9.001) Küche_Temperatur
knx.0 | 2021-07-19 23:24:41.856 | info | (1297) ( 3.2 ) Received TUNNEL_REQUEST (WRITE - send ACK ) : 06 10 04 20 00 17 04 42 00 00 29 00 bc e0 11 11 29 03 03 00 80 0c bf ChID: 0
knx.0 | 2021-07-19 23:24:40.914 | silly | (1297) States user redis pmessage knx.0.*/knx.0.Sensoren.EG.Küche_Temperatur:{"val":24.3,"ack":true,"ts":1626729880911,"q":0,"from":"system.adapter.knx.0","user":"system.user.admin","lc":1626728845974
knx.0 | 2021-07-19 23:24:40.909 | info | (1297) STATE_TUNNELING_REQUEST : no defined handling for transition from State: STATE_NOT_CONNECTED(0) to STATE_TUNNELLING_REQUEST(13).
knx.0 | 2021-07-19 23:24:40.908 | info | (1297) Change state from STATE_NOT_CONNECTED(0) to STATE_TUNNELLING_REQUEST(13)
knx.0 | 2021-07-19 23:24:40.905 | info | (1297) WRITE : mappedName : Küche Temperatur dest : 5/1/3 val: 24.3 (DPT9.001) Küche_Temperatur
knx.0 | 2021-07-19 23:24:40.897 | info | (1297) ( 3.2 ) Received TUNNEL_REQUEST (WRITE - send ACK ) : 06 10 04 20 00 17 04 42 00 00 29 00 bc e0 11 11 29 03 03 00 80 0c bf ChID: 0
knx.0 | 2021-07-19 23:24:39.438 | info | (1297) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 2021-07-19 23:24:39.437 | info | (1297) ... not able to close connection, because already closed
knx.0 | 2021-07-19 23:24:39.436 | info | (1297) Connection persists.....closing now
knx.0 | 2021-07-19 23:24:39.435 | info | (1297) Change state from STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0)
knx.0 | 2021-07-19 23:24:37.434 | info | (1297) Change state from STATE_PORT_OPENED(2) to STATE_CONNECT_REQUEST(3)
knx.0 | 2021-07-19 23:24:37.434 | info | (1297) Send : UDP Connection Request : 06 10 02 05 00 1a 08 01 ac 1e 00 02 e2 f8 08 01 00 00 00 00 e2 f8 04 04 02 00 sent to 192.168.1.55:3671
knx.0 | 2021-07-19 23:24:37.431 | info | (1297) Connected - local UDP Server listening on 172.30.0.2:58104
knx.0 | 2021-07-19 23:24:37.426 | info | (1297) Change state from STATE_OPENING_PORT(1) to STATE_PORT_OPENED(2)
knx.0 | 2021-07-19 23:24:37.425 | info | (1297) Event : UDP - listening
knx.0 | 2021-07-19 23:24:37.421 | info | (1297) Debuglevel: 3 4
knx.0 | 2021-07-19 23:24:37.412 | info | (1297) Connecting to knx GW: 192.168.1.55:3671 with phy. Adr: 1.1.255
knx.0 | 2021-07-19 23:24:37.411 | silly | (1297) redis psubscribe cfg.o.enum.rooms
knx.0 | 2021-07-19 23:24:37.408 | info | (1297) knx license is OK.
knx.0 | 2021-07-19 23:24:37.283 | silly | (1297) States system redis pmessage system.adapter.knx.0.logLevel/system.adapter.knx.0.logLevel:{"val":"silly","ack":true,"ts":1626729877220,"q":0,"from":"system.adapter.knx.0","lc":1626374323569}
knx.0 | 2021-07-19 23:24:37.191 | info | (1297) starting. Version 1.0.45 in /opt/iobroker/node_modules/iobroker.knx, node: v12.22.2, js-controller: 3.1.6
host.iobroker | 2021-07-19 23:24:35.588 | info | instance system.adapter.knx.0 started with pid 1297
host.iobroker | 2021-07-19 23:24:35.566 | info | "system.adapter.knx.0" enabled
```

After some tries, the connection is established and some objects (like  5/1/3, the kitchen temperature) are filled with data from the KNX bus. So I asume that the connection is working properly. But the state circle in the instance list is yellow (connected to host, health check, but NO connection to KNX)?!? Is this normal? What can I do to "fix" this? I use an Enertex IP Interface (Tunnel) to connect to the KNX bus, iobroker is running inside a docker container.

If I change the state of one manually in the Object browser (say turn on a light by setting the state from false to true in the object browser), I've got the following messages in the log:

```
knx.0 | 2021-07-19 23:48:42.521 | info | (2284) BINARY CHANGE change from true to 1
-- | -- | -- | --
knx.0 | 2021-07-19 23:48:42.521 | info | (2284) main.js : tGA.write on Statechange : 1/1/1 P-038E-0_GA-167 typeof val: boolean true DPT1.001
knx.0 | 2021-07-19 23:48:42.519 | silly | (2284) States user redis pmessage knx.0.*/knx.0.Beleuchtung.EG.Bad_Deckenlichter_(alle):{"val":true,"ack":false,"ts":1626731322518,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc"
```

I've captured the traffic with wireshark. The connection will be established, but no message will be sent to the KNX bus after changing the state.

![image](https://user-images.githubusercontent.com/121972/126235297-82680fd7-0989-41a9-9ab9-a034b6c05d98.png)

Same observation can be made on the ETS software when I monitor the KNX bus. So it seems there is a problem on the iobroker side. Is there any way to debug this further?

Another strange message appear from time to time:

```
2284) STATE_TUNNELING_REQUEST: analyse this case. Gateway sends the same package one more time, may be answer???
```

Not sure what this means.

**Comment by chefkoch009** [comment]
the connection test was to aggressive. This is fixed in upcoming Version.

**Comment by f0086** [comment]
Can you please link to the commit so I can see it?
The problem remains on my system :(
