### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by mghomedev** [ioBroker/ioBroker.knx#66]
Since I updated to the latest KNX-adapter version today, I get this new error after each import:

nx.0	2019-08-24 21:14:58.573	error	at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
knx.0	2019-08-24 21:14:58.573	error	at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3681:34)
knx.0	2019-08-24 21:14:58.573	error	at Adapter.emit (events.js:198:13)
knx.0	2019-08-24 21:14:58.573	error	at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:79:7121)
knx.0	2019-08-24 21:14:58.573	error	at _0x35f3b6 (/opt/iobroker/node_modules/iobroker.knx/knx.js:79:8475)
knx.0	2019-08-24 21:14:58.573	error	at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:71:13379)
knx.0	2019-08-24 21:14:58.573	error	at Object._0x790e9f [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:43:37404)
knx.0	2019-08-24 21:14:58.573	error	at _0x2b332a (/opt/iobroker/node_modules/iobroker.knx/knx.js:43:36509)
knx.0	2019-08-24 21:14:58.573	error	at _0x1c793e (/opt/iobroker/node_modules/iobroker.knx/knx.js:43:36167)
knx.0	2019-08-24 21:14:58.573	error	at _0x21c95e (/opt/iobroker/node_modules/iobroker.knx/knx.js:43:3528)
knx.0	2019-08-24 21:14:58.573	error	TypeError: Cannot read property 'replace' of undefined
knx.0	2019-08-24 21:14:58.572	error	message messagebox.system.adapter.knx.0 [object Object] Cannot read property 'replace' of undefined

**Comment by chefkoch009** [comment]
Thanks for your Report. I recognized, the the ets5.7.2 Export Layout depends on the ETS Version on that the project was created. That means 4.6.x->5.7.2 !== 5.5.x->5.7.2. !== 5.7.2->5.7.2. 
Do you remember, what‘s your create-project-Version was? And did you have ETS Versions between creation and 5.7.2. Exports? Did you also get this error wühle importing 5.5.x Version?

**Comment by mghomedev** [comment]
My project was initially created with ETS 5.6.4 over 1 year ago. Then ETS and the project was always updated to each ETS version that became available. Sine April 2019 I use ETS 5.7.2 and the error was from the project exported from ETS 5.7.2 version. But I am quite sure that the error did not come before I updated the knxd yesterday.

**Comment by chefkoch009** [comment]
The IoBroker KNX Adapter nothing to do knxd except the communication as like other KNX-LAN devices. I think you mean the IoBroker Adapter. In that case you are right. Since Version 1.0.3x matches the new importer only for ETS versions =5.7.2. otherwise the old importer Works.

**Comment by mghomedev** [comment]
Yes, I fixed my comment. I hope you can fix the issue

**Comment by chefkoch009** [comment]
Still on process.

**Comment by chefkoch009** [comment]
Please update this issue, if problem persists with Version 1.0.32.

**Comment by mghomedev** [comment]
The problem persists. In fact I had to downgrade now back to the old version 1.0.20, which was the last one without the problem to import my .knxproj file correctly. Starting from 1.0.30 it did not create all states because it crashed during import with this message. It is exactly the same project file

**Comment by mghomedev** [comment]
> Please update this issue, if problem persists with Version 1.0.33
This new version also crashes 

knx.0	2019-09-14 21:16:52.918	error	at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
knx.0	2019-09-14 21:16:52.918	error	at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3681:34)
knx.0	2019-09-14 21:16:52.918	error	at Adapter.emit (events.js:198:13)
knx.0	2019-09-14 21:16:52.918	error	at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:7068)
knx.0	2019-09-14 21:16:52.918	error	at _0x3ae518 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8390)
knx.0	2019-09-14 21:16:52.918	error	at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13460)
knx.0	2019-09-14 21:16:52.918	error	at Object._0xca2d83 [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:39579)
knx.0	2019-09-14 21:16:52.918	error	at _0x5b7f4b (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:38415)
knx.0	2019-09-14 21:16:52.918	error	at _0x2f51ee (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:38086)
knx.0	2019-09-14 21:16:52.918	error	at _0x295f9a (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:3507)
knx.0	2019-09-14 21:16:52.918	error	TypeError: Cannot read property 'replace' of undefined
knx.0	2019-09-14 21:16:52.918	error	message messagebox.system.adapter.knx.0 [object Object] Cannot read property 'replace' of undefined

**Comment by mghomedev** [comment]
The problem also still happens in 1.0.35 .  I guess I have to downgrade again to 1.0.2x where it works.


knx.0 | 2019-09-28 19:49:58.660 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
-- | -- | -- | --
knx.0 | 2019-09-28 19:49:58.660 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3681:34)
knx.0 | 2019-09-28 19:49:58.660 | error | at Adapter.emit (events.js:198:13)
knx.0 | 2019-09-28 19:49:58.660 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:7324)
knx.0 | 2019-09-28 19:49:58.660 | error | at _0x3e1e1e (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8688)
knx.0 | 2019-09-28 19:49:58.660 | error | at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13449)
knx.0 | 2019-09-28 19:49:58.660 | error | at Object._0xfdb812 [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:39748)
knx.0 | 2019-09-28 19:49:58.660 | error | at _0x154d89 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:38285)
knx.0 | 2019-09-28 19:49:58.660 | error | at _0x18f7c5 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:37950)
knx.0 | 2019-09-28 19:49:58.660 | error | at _0x28c4f1 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:3549)
knx.0 | 2019-09-28 19:49:58.660 | error | TypeError: Cannot read property 'replace' of undefined
knx.0 | 2019-09-28 19:49:58.659 | error | message messagebox.system.adapter.knx.0 [object Object] Cannot read property 'replace' of undefined

**Comment by mghomedev** [comment]
I still get that with 1.0.39


knx.0 | 2020-03-04 21:15:47.198 | warn | at Immediate.setImmediate [as _onImmediate]  (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:227:41)
-- | -- | -- | --
knx.0 | 2020-03-04 21:15:47.198 | warn | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4808:34)
knx.0 | 2020-03-04 21:15:47.198 | warn | at Adapter.emit (events.js:198:13)
knx.0 | 2020-03-04 21:15:47.198 | warn | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:7072)
knx.0 | 2020-03-04 21:15:47.198 | warn | at _0x465449 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8493)
knx.0 | 2020-03-04 21:15:47.198 | warn | at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13499)
knx.0 | 2020-03-04 21:15:47.198 | warn | at Object._0x3a7cff [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:40526)
knx.0 | 2020-03-04 21:15:47.198 | warn | at _0x2caea3 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:38907)
knx.0 | 2020-03-04 21:15:47.198 | warn | at _0x4081bb (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:38576)
knx.0 | 2020-03-04 21:15:47.198 | warn | at _0x3dee37 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:3508)
knx.0 | 2020-03-04 21:15:47.198 | warn | (9571) TypeError: Cannot read property 'replace' of undefined
knx.0 | 2020-03-04 21:15:47.197 | warn | (9571) States system pmessage io.messagebox.system.adapter.knx.0  {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":367,"ack":false,"time":158

**Comment by chefkoch009** [comment]
can I get your proj-file?

**Comment by chefkoch009** [comment]
is fixed in new version

**Comment by mghomedev** [comment]
Yes, this issue seems to be solved for me in 1.0.42, thanks!
